name: Publish to GitHub releases
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to release'
        required: true
      quality:
        description: 'Quality: nightly or stable'
        required: true
        default: stable
      uploadRelease:
        description: 'Create GitHub Release'
        required: false
        default: "false"
  workflow_run:
    workflows: ["Nightly"]
    types: [completed]

env:
  QUALITY: ${{ github.event.inputs.quality || 'nightly' }}
  RELEASE_COMMIT: ${{ github.event.inputs.commit || 'main' }}

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-18.04, macos-11, windows-latest]
        # support only ubuntu for now
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}      
    if: github.event.inputs.commit || github.event.workflow_run.conclusion == 'success'
    steps:  
      - uses: actions/checkout@v2
        with:
          repository: gitpod-io/openvscode-server
          ref: ${{ env.RELEASE_COMMIT }}
          path: openvscode-server
          token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
        with:
          repository: enz0nun3s15/vscode-server
          path: myvscode
          token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
      
      - name: Change product.json
        run: |
          ls -a
          mv ./myvscode/product.json ./openvscode-server/product.json

      - name: Setup Build Environment
        working-directory: ./openvscode-server
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
          sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Compute node modules cache key
        working-directory: ./openvscode-server
        id: nodeModulesCacheKey
        run: echo "::set-output name=value::$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js)"
      - name: Cache node modules
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: "openvscode-server/**/node_modules"
          key: ${{ runner.os }}-cacheNodeModules14-${{ steps.nodeModulesCacheKey.outputs.value }}
          restore-keys: ${{ runner.os }}-cacheNodeModules14-
      - name: Get yarn cache directory path
        working-directory: ./openvscode-server
        id: yarnCacheDirPath
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn directory
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
          key: ${{ runner.os }}-yarnCacheDir-${{ steps.nodeModulesCacheKey.outputs.value }}
          restore-keys: ${{ runner.os }}-yarnCacheDir-
      - name: Execute yarn
        working-directory: ./openvscode-server
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: yarn --frozen-lockfile --network-timeout 180000
      
      - name: Prepare for distribution
        working-directory: ./openvscode-server
        run: yarn gulp server-min
      
      - name: Download playwright
        working-directory: ./openvscode-server
        run: |
          yarn playwright-install 

      - name: Determine archive filename
        uses: haya14busa/action-cond@v1
        id: archive
        with:
          cond: ${{ runner.os == 'Windows' }}
          if_true: 'zip'
          if_false: 'tar.gz'
      
      - name: Set environment variables (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          echo "EXTENSION=${{ steps.archive.outputs.value }}" >> $GITHUB_ENV
          echo "VERSION=$(node -p -e "require('./openvscode-server/package.json').version")" >> $GITHUB_ENV
      
      - name: Set archive file name
        run: |
          os_name=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
          quality_name=$([ "$QUALITY" == "nightly" ] && echo "-nightly" || echo "")
          name="openvscode-server${quality_name}-v${VERSION}-${os_name}-x64"
          echo "ARCHIVE_NAME=$name" >> $GITHUB_ENV
          echo "ARCHIVE_FULL_NAME=$name.$EXTENSION" >> $GITHUB_ENV
      
      - name: Rename the bundle file
        run: |
          mv server-pkg/ ${{ env.ARCHIVE_NAME }}/
      
      - name: Bundle tarfile
        if: runner.os != 'Windows'
        run: |
          sudo tar cfzv ${{ env.ARCHIVE_FULL_NAME }} ${{ env.ARCHIVE_NAME }}/ > /dev/null
      
      - name: Archive sanity check
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-x64
          path: ${{ env.ARCHIVE_FULL_NAME }}
  
  upload:
    needs: build 
    runs-on: ubuntu-latest
    name: Create the release
    if: github.event.inputs.uploadRelease == 'true' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: outputs/
      
      - run: |
          echo "VERSION=$(ls outputs/Linux-x64 | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')" >> $GITHUB_ENV
      
      - name: Create stable release
        if: env.QUALITY == 'stable'
        uses: softprops/action-gh-release@v1
        with:
          repository: enz0nun3s15/vscode-server
          target_commitish: ${{ env.RELEASE_COMMIT }}
          body: OpenVSCode Server v${{ env.VERSION }}
          token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
          files: |
            outputs/**/*.tar.gz

      - name: Sleep
        if: env.QUALITY == 'nightly'
        run: sleep 30s
